<a href="https://colab.research.google.com/github/prokope/learning-data-science/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetores como dados

## Ideia central


- Um vetor representa uma observação
- Cada componente representa uma variável (feature)

## Exemplos conceituais

- Pessoa -> (idade, altura)
- Produto -> (preço, avaliação, vendas)

## Criando um vetor com NumPy

In [1]:
import numpy as np

pessoa = np.array([25, 1.75])

pessoa

array([25.  ,  1.75])

In [3]:
# Vários vetores (matriz) de dados

dados = np.array([
    [30, 1.77],
    [17, 1.83],
    [24, 1.65]
])

dados

array([[30.  ,  1.77],
       [17.  ,  1.83],
       [24.  ,  1.65]])

In [5]:
# Transformando isso num DF do Pandas

import pandas as pd

df = pd.DataFrame(dados, columns=["idade", "altura"])

df

# Cada linha do DF é um vetor
# Cada elemento da linha é uma feature daquele vetor
# Dataset = Matriz

idade  altura
0   30.0    1.77
1   17.0    1.83
2   24.0    1.65

**🎯 Resumo: Tudo que o Python faz é tornar a Álgebra Linear manipulável.**

# Operações vetoriais básicas

## Ideia central

**Operações vetoriais permitem combinar, comparar e transformar dados.**

Em Data Science, elas aparecem como:
- Comparação entre observações
- Ajustes de escala
- Construção de modelos lineares

## Soma de vetores

Interpretação:
- Ideal para tirar média e fazer agregações
- Soma componente a componente (a1 + b1, a2 + b2)

In [7]:
pessoa_a = np.array([25, 1.77, 5100])
pessoa_b = np.array([22, 1.70, 3100])

# Ajuste visual
np.set_printoptions(suppress=True)

pessoa_a + pessoa_b

array([  47.  ,    3.47, 8200.  ])